### ISSUE TITLE
ISSUE WITH Xiaomi Redmi Note 12 Pro Ultra Mega Dark Killer Ultimate Superphone Deluxe Special Edition with 5G Network and AI-Enhanced Camera, The Grand Master of All Smartphones, The Ultimate Flagship Phone of the Decade, The Most Powerful Device with Lightning-Fast Octa-Core Processor, Massive 16GB RAM and 2TB Storage, The Device with Stunning 7.5-inch QHD+ Super AMOLED Display with HDR and Dolby Vision Support, The Most Durable Phone with IP68 Rating, The Masterpiece of Photography with 108MP Ultra-Premium Main Lens, 64MP Ultra-Wide-Angle Lens, 32MP Super Zoom Lens, and 16MP Macro Lens, The Phone with Insane Battery Life of 8000mAh, The Most Advanced Phone with Facial Recognition, Fingerprint Scanner, Wireless Charging, and 5G Connectivity.

### ISSUE THREAD

**Issue by Nester44** [michigang1/to-do-list-android#2]
НЕ ЗАПУСКАЕТСЯ НА МОЁМ Xiaomi Redmi Note 12 Pro Ultra Mega Dark Killer Ultimate Superphone Deluxe Special Edition with 5G Network and AI-Enhanced Camera, The Grand Master of All Smartphones, The Ultimate Flagship Phone of the Decade, The Most Powerful Device with Lightning-Fast Octa-Core Processor, Massive 16GB RAM and 2TB Storage, The Device with Stunning 7.5-inch QHD+ Super AMOLED Display with HDR and Dolby Vision Support, The Most Durable Phone with IP68 Rating, The Masterpiece of Photography with 108MP Ultra-Premium Main Lens, 64MP Ultra-Wide-Angle Lens, 32MP Super Zoom Lens, and 16MP Macro Lens, The Phone with Insane Battery Life of 8000mAh, The Most Advanced Phone with Facial Recognition, Fingerprint Scanner, Wireless Charging, and 5G Connectivity. 
Требую деньги обратно!

**Comment by michigang1** [comment]
It isn't delightful. After all, we conducted manual tests on all models of Xiaomi phones. Could you describe the problem in more detail?

Sincerely, Mykhailo Chirozidi

(razrab pidoras)
